### ISSUE TITLE
Function support?

### ISSUE THREAD

**Issue by Gabilabrebi** [julienetie/vscode-template-literals#2]
Hello

Would it be possible to add support for function? I really like this expansion and the fact it does not require prefix, but it breaks my code higlighting everytime i put a template string in a function :(

Thanks for the great work

**Comment by julienetie** [comment]
This would be ideal, I've not had a lot of time but I'll explore how the regex can be improved. 
Help would be welcomed.

**Comment by julienetie** [comment]
I've decided to change the way the plugin works
https://github.com/julienetie/vscode-template-literals/issues/4
