### ISSUE TITLE
No highlighting when inline html script

### ISSUE THREAD

**Issue by modmoto** [julienetie/vscode-template-literals#4]
Something like this here does not get higlighted, while it works in a `.js` file. My guess is, that html files are excluded? Would be cool to have it there aswell. Thanks for the plugin, the first that is actually working xD

![image](https://user-images.githubusercontent.com/9074759/229101958-2d46ce5f-cafe-4b30-b79c-d8d158147bf4.png)

**Comment by julienetie** [comment]
Sorry for the delay, I've decided to change the approach which requires a pass-though for `_` , `html` or `svg`
